# Site
name: "Cellar of Sounds and Words"
title: "Cellar of Sounds and Words"
description: "Cellar of Sounds and Words"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: ''
google_analytics: '234778001'
disqus: 'demowebsite'
mailchimp-list: 'https://daduki.github.io'
include: ["_pages"]
permalink: /:title/
email: daduki@gmail.com

# Authors
authors:
  emstudio:
    name: emstudio
    display_name: EmStudio
    avatar: 'assets/images/emstudio_avatar.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: daduki@gmail.com
    web: https://www.melon.com/artist/timeline.htm?artistId=221803
    twitter: https://twitter.com/caferoman
    description: "@emstudio : Modern Folk Singer Songwriter"
  caferoman:
    name: caferoman
    display_name: Caferoman
    avatar: 'assets/images/caferoman_avatar.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: daduki@gmail.com
    web: https://steempeak.com/@caferoman
    twitter: https://twitter.com/caferoman
    description: "@caferoman : Book Reviewer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3739397756903205"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
